FROM openjdk:8u102-jdk

RUN mkdir /shared-folder
RUN mkdir /conf

ARG JAR_DIR=/usr/local/lib

# Mend traceability labels
LABEL io.mend.image.dockerfile.path=frontend/Dockerfile.fe
LABEL org.opencontainers.image.source=https://github.com/lukebrogan-mend/tracing-demo-recording

ENTRYPOINT ["./myapp"]
